[project]
name = "diplomado-ciencia-datos-mide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair[all]>=6.2.2",
    "duckdb>=1.5.5",
    "ipython>=9.15.0",
    "marimo[recommended]>=0.23.15",
    "matplotlib>=3.11.1",
    "notebook>=7.6.1",
    "polars[all]>=1.43.0",
]
